In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
# 데이터 적재

In [2]:
# load_lris()가 반환한 객체는 dictonary와 유사한 Bunch 의 객체, 키와 값으로 구성되어 있음

In [3]:
print('iris_dataset의 key:\n', iris_dataset.keys())

iris_dataset의 key:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
# Descp(description) 키에는 데이터셋에 대한 간단한 설명이 들어 있음

In [5]:
print(iris_dataset['DESCR'][:193])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre


In [6]:
print('타깃의 이름 :',iris_dataset['target_names'])

타깃의 이름 : ['setosa' 'versicolor' 'virginica']


In [7]:
print('특성의 이름 :',iris_dataset['feature_names'])

특성의 이름 : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
#실제 데이터는 target과 data 필드에 들어가 있음
#data는 꽃잎의 길이와 폭 1,2
#꽃받침의 길이와 폭을 3,4
#수치 값으로 가지고 있는 Numpy 배열
print(type(iris_dataset['data']))
iris_dataset['data'].shape
# 150개의 꽃(샘플), 각 꽃에서 구한 측정치_속성(특성)

<class 'numpy.ndarray'>


(150, 4)

In [9]:
print('data의 첫 다섯행:\n', iris_dataset['data'][:5])

data의 첫 다섯행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
# 이와 같은 데이터 셋은 품종을 정확하게 분류한 데이터를 가지고 있기 때문에 지도 학습에 속한다.
# 즉 분류(Classification)문제에 속함, 출력될 수 있는 꽃들의 품종은 클래스에 속한다
# 데이터 포인트 하나(붓꽃 하나)에 대한 기대 출력은 꽃의 품중이 됩니다.
# 이런 특정 데이터 포인트에 대한 출력, 즉 품종(answer)을 레이블(label)이라고 합니다

In [11]:
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
print('타깃의 이름 :',iris_dataset['target_names'])
# 각각 0,1,2 라벨링

타깃의 이름 : ['setosa' 'versicolor' 'virginica']


In [13]:
# 이 데이터를 통해 들어오는 값에 따라서 꽃의 종류를 분류하는 머신 러닝 모델을 만들겠음
# 새 데이터에 적용하기 전에 잘 작동하는지, (만든 모델의 예측을 신뢰할 수 있는지 알아보아야함)

In [14]:
# 학습에 사용한 데이터를 사용해서 실제 성능을 측정하는 것은 옳지 않음, 세 데이터를 모델에 적용시켜보아야..
# 따라서 보편적으로 가지고 있는 데이터를 두 그룹 (train, test)으로 나눠서 사용하는 것이 일반적
# scikit-learn은 데이터 셋을 섞어서 나눠주는 train_test_split 함수를 지원, 유용하게 사용할 수 있을 것_ 대게는 75%를 학습, 25%를 테스트로 사용
# * train_test_split 함수에서 test_size 매개변수로 테스트 세트의 비율을 지정할 수 있음

In [15]:
# 보편적으로 데이터는 X, 레이블(라벨)은 y로 표기한다.

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)
# train_test_split 함수로 데이터를 나누기 전에 유사 난수 생성기를 사용해, 데이터 셋을 무작위로 섞어야함
# 이 함수를 여러번 실행해도 같은 결과가 나오도록 유사 난수 생성기에 넣을 난수 초기값을 random_state 매개변수로 전달함

In [17]:
# train_test_split 함수의 반환값은 X_train, X_test, y_train, y_test 이며, 모두 Numpy 배열..
# X_train은 전체 데이터의 75% X_test은 25%를 담고 있음

In [18]:
print('X_train shape : {} y_train shape : {}'.format(X_train.shape, y_train.shape))
print('X_test shape : {} y_test shape : {}'.format(X_test.shape, y_test.shape))

X_train shape : (112, 4) y_train shape : (112,)
X_test shape : (38, 4) y_test shape : (38,)


In [19]:
y_test
# 이와같이 섞여있다 

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])